In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler,LabelEncoder
from sklearn.metrics import mean_absolute_error as mae, mean_squared_error as mse,r2_score
import math
from pycaret.regression import *

from tensorflow import keras

In [3]:
data = pd.read_excel('../data/Processed_data_noZero.xlsx') 
data = data.loc[:, ~data.columns.str.contains('^Unnamed')]
data.head()

,Test Time,Roll Speed,Eng. Speed,CO Mass,NOx Mass,CO2 Mass,driving cycle,Vehicle
0,6.1,0.054110,863.487,3.345830e-10,0.000004,0.327586,Urban-Free,1
1,8.1,0.007586,872.968,4.586630e-09,0.000005,0.326265,Urban-Free,1
2,10.1,0.083947,861.854,3.301040e-10,0.000004,0.323550,Urban-Free,1
3,11.1,0.031859,869.703,3.341100e-10,0.000004,0.327409,Urban-Free,1
4,12.1,0.038939,863.675,2.337160e-09,0.000004,0.333081,Urban-Free,1

In [10]:
exp_reg101 = setup(data = data[['Roll Speed','Eng. Speed','CO Mass','driving cycle ','Vehicle']],
                    target = 'CO Mass', session_id=123)

In [11]:
best = compare_models()